server:
  port: 80

warehouse:
  path: /Users/liangzhanbo/Downloads/

spring:
  thymeleaf:
    mode: HTML
    cache: true
    prefix: classpath:/templates
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///huyi_piedpiper?serverTimezone=UTC
    username: root
    password: Mysqlrt123456

